### ISSUE TITLE
Bug report: GridVectors error with certain MODIS data files 

### ISSUE THREAD

**Issue by jemissik** [jemissik/movebank_vis#28]
**Describe the bug**
The animator is throwing an error for certain MODIS data files. The file in question looks fine when viewing in the python app. If the file is resampled to another frequency (tested 1-day and 5-day) using the python app, then it works in the animator.

**Error log**
Error using griddedInterpolant
GridVectors must define a grid whose size is compatible with the Values array.

Error in m_image (line 149)

Error in animate_gridded_ndvi (line 147)

Error in gridded_data_animation/CreateanimationButtonPushed (line 482)

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)

**Desktop (please complete the following information):**

 - OS: macOS Ventura
 - Version 13.0

**Additional context**
[Konda_ndvi_MOD13Q1.006_250m_aid0001.nc.zip](https://github.com/jemissik/movebank_vis/files/10180427/Konda_ndvi_MOD13Q1.006_250m_aid0001.nc.zip)

**Comment by sarahcd** [comment]
I get the same error with both .ncs I got through Appeears. Example attached:
[MOD10A2.061_500m_aid0001.nc.zip](https://github.com/jemissik/movebank_vis/files/10467599/MOD10A2.061_500m_aid0001.nc.zip)

This file is exactly as retrieved from Appeears. Do the raster data need to be resampled to match the track frequency chosen in the Tracks Visualization Options, prior to putting them into the Animate tool?

**Comment by jemissik** [comment]
I will have to investigate this further. Could you send the track data you were using for this example? 

The raster data shouldn't need to match the track frequency if you're not plotting contour data (the contour time series still needs to be fixed, see #29). Resampling the data in the gridded data python app before giving it to Animate tool fixed the problem for the case I looked at before, but the gridded data app also does some other things to try to sanitize/prepare the data for the Animate tool.
