### ISSUE TITLE
error received despite (I think) successful processing

### ISSUE THREAD

**Issue by sarahcd** [jemissik/movebank_vis#34]
**Describe the bug**
I received the error below at/toward the end of creating an animation. However, it seems to have successfully created and saved all the frame images. 

**To Reproduce**
Can try to reproduce and document if you need more detail. As input I had track and gridded data, no other files, no elevation contours. I manually adjusted the geographic extent under 'animal track data' because previous attempts had let to large white regions outside the range of the gridded data.

**Error log**
Error using matlab.internal.imagesci.netcdflib
Input argument out of range.

Error in netcdf.getVar (line 205)

Error in internal.matlab.imagesci.nc/read (line 674)

Error in ncread (line 74)

Error in read_nc_timestamps (line 30)

Error in unpack_netcdf (line 40)

Error in animate_gridded_ndvi (line 120)

Error in gridded_data_animation/CreateanimationButtonPushed (line 482)

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 
 - Version 12.0.1

**Comment by jemissik** [comment]
Would you be able to send the data and settings you used so I can try to reproduce the error?

**Comment by sarahcd** [comment]
I haven't encountered it again so I think we can close it. I'll re-report if I see it again.
